#   ___        _     
#  / _ \ _   _(_)____
# | | | | | | | |_  /
# | |_| | |_| | |/ / 
#  \__\_\\__,_|_/___|
                   
  - name: "quiz"
    label: "Quiz"
    identifier_field: "pilz"
    folder: "_quiz"
    label_singular: "Quizfrage"
    editor:
      preview: false
    create: true
    sortable_fields: "pilz"
    fields:
      - label: "Bild"
        name: "bild"
        widget: "image"
      - label: "Pilz"
        name: "pilz"
        widget: "relation"
        collection: "pilze"
        valueField: "beschreibung.wissenschaftlich"
        searchFields: ["beschreibung.wissenschaftlich", "beschreibung.deutsch"]
        displayFields: ["beschreibung.wissenschaftlich", "beschreibung.deutsch"]

#   ____ _                          
#  / ___| | ___  ___ ___  __ _ _ __ 
# | |  _| |/ _ \/ __/ __|/ _` | '__|
# | |_| | | (_) \__ \__ \ (_| | |   
#  \____|_|\___/|___/___/\__,_|_|   

  - name: "glossar"
    label: "Glossar"
    identifier_field: "schlagwort"
    folder: "_glossar"
    label_singular: "Glossareintrag"
    editor:
      preview: false
    create: true
    sortable_fields: ["schlagwort", "synonym"]
    fields:
      - {label: "Schlagwort", name: "schlagwort", widget: "string"}
      - {label: "Synonym(e)", name: "synonym", widget: "string", required: false}
      - {label: "Defnition", name: "definition", widget: "markdown"}
